#springboot整合数据库员的连接参数
spring:
  application:
    name: springboot_mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kanyi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456789
    type: com.alibaba.druid.pool.DruidDataSource

#    mvc:
#      view:
#        # 页面默认前缀目录
#        prefix: /WEB-INF/viwes/
#        # 响应页面默认后缀
#        suffix: .jsp

mybatis:
  #映射文件的加载位置
  mapper-locations: classpath:mappers/*.xml
  #实体的别名
  type-aliases-package: com.kangyi.pojo
  #允许驼峰式命名
  configuration:
    map-underscore-to-camel-case: true

#  servlet:
#    session:
#      timeout: 3600s


#server:
#  session:
#    tracking-modes: cookie


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false


  # redis配置
  redis:
    host: localhost
    port: 6379
    password:

  # 缓存
  cache:
    type: simple
    cache-names: cache_post